name: My First Workflow
on: workflow_dispatch
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
     - name: Greetings And Explore Runner
       run: |
            echo "Hello World!"
            echo
            echo "***********CPU Details**********"
            lscpu
            echo "***********End Of CPU Details***********"
            echo
            echo "***********Memory Details**********"
            free -m
            echo "***********End Of Memory Details***********"
            echo
            echo "***********Storage Details**********"
            lsblk
            df -h
            echo "***********End Of Storage Details***********"
            echo
            whoami
      

