name: My First Workflow
on: workflow_dispatch
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
     - name: Greetings
       run: echo "Hello World!"
     - name: Explore Runner
       run: lscpu && free -m && df -h
     - name: Explore Directories
       run: ls -l /mnt && du -sh /mnt && ls -l / && du -sh /